default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PETS_DATABASE_HOST'] %>
  port: <%= ENV['PETS_DATABASE_PORT'] %>
  username: <%= ENV['PETS_DATABASE_USER'] %>
  password: <%= ENV['PETS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: pets_development

test:
  <<: *default
  database: pets_test

staging:
  <<: *default
  database: pets_staging

production:
  <<: *default
  database: pets_production
